//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAP.EjemplarWSClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSEjemplarModel", Namespace="http://schemas.datacontract.org/2004/07/WcfBiblioteca")]
    [System.SerializableAttribute()]
    public partial class WSEjemplarModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FPublicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumPaginasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FPublicacion {
            get {
                return this.FPublicacionField;
            }
            set {
                if ((this.FPublicacionField.Equals(value) != true)) {
                    this.FPublicacionField = value;
                    this.RaisePropertyChanged("FPublicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumPaginas {
            get {
                return this.NumPaginasField;
            }
            set {
                if ((this.NumPaginasField.Equals(value) != true)) {
                    this.NumPaginasField = value;
                    this.RaisePropertyChanged("NumPaginas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EjemplarWSClient.IWSEjemplar")]
    public interface IWSEjemplar {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEjemplar/Create", ReplyAction="http://tempuri.org/IWSEjemplar/CreateResponse")]
        SOAP.EjemplarWSClient.WSEjemplarModel Create(SOAP.EjemplarWSClient.WSEjemplarModel WSEjemplarModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEjemplar/Create", ReplyAction="http://tempuri.org/IWSEjemplar/CreateResponse")]
        System.Threading.Tasks.Task<SOAP.EjemplarWSClient.WSEjemplarModel> CreateAsync(SOAP.EjemplarWSClient.WSEjemplarModel WSEjemplarModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEjemplar/Update", ReplyAction="http://tempuri.org/IWSEjemplar/UpdateResponse")]
        SOAP.EjemplarWSClient.WSEjemplarModel Update(SOAP.EjemplarWSClient.WSEjemplarModel WSEjemplarModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEjemplar/Update", ReplyAction="http://tempuri.org/IWSEjemplar/UpdateResponse")]
        System.Threading.Tasks.Task<SOAP.EjemplarWSClient.WSEjemplarModel> UpdateAsync(SOAP.EjemplarWSClient.WSEjemplarModel WSEjemplarModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEjemplar/Delete", ReplyAction="http://tempuri.org/IWSEjemplar/DeleteResponse")]
        void Delete(int codEjemplar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEjemplar/Delete", ReplyAction="http://tempuri.org/IWSEjemplar/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int codEjemplar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEjemplar/GetAll", ReplyAction="http://tempuri.org/IWSEjemplar/GetAllResponse")]
        SOAP.EjemplarWSClient.WSEjemplarModel[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEjemplar/GetAll", ReplyAction="http://tempuri.org/IWSEjemplar/GetAllResponse")]
        System.Threading.Tasks.Task<SOAP.EjemplarWSClient.WSEjemplarModel[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEjemplar/GetById", ReplyAction="http://tempuri.org/IWSEjemplar/GetByIdResponse")]
        SOAP.EjemplarWSClient.WSEjemplarModel GetById(int codEjemplar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEjemplar/GetById", ReplyAction="http://tempuri.org/IWSEjemplar/GetByIdResponse")]
        System.Threading.Tasks.Task<SOAP.EjemplarWSClient.WSEjemplarModel> GetByIdAsync(int codEjemplar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSEjemplarChannel : SOAP.EjemplarWSClient.IWSEjemplar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSEjemplarClient : System.ServiceModel.ClientBase<SOAP.EjemplarWSClient.IWSEjemplar>, SOAP.EjemplarWSClient.IWSEjemplar {
        
        public WSEjemplarClient() {
        }
        
        public WSEjemplarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSEjemplarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEjemplarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEjemplarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAP.EjemplarWSClient.WSEjemplarModel Create(SOAP.EjemplarWSClient.WSEjemplarModel WSEjemplarModel) {
            return base.Channel.Create(WSEjemplarModel);
        }
        
        public System.Threading.Tasks.Task<SOAP.EjemplarWSClient.WSEjemplarModel> CreateAsync(SOAP.EjemplarWSClient.WSEjemplarModel WSEjemplarModel) {
            return base.Channel.CreateAsync(WSEjemplarModel);
        }
        
        public SOAP.EjemplarWSClient.WSEjemplarModel Update(SOAP.EjemplarWSClient.WSEjemplarModel WSEjemplarModel) {
            return base.Channel.Update(WSEjemplarModel);
        }
        
        public System.Threading.Tasks.Task<SOAP.EjemplarWSClient.WSEjemplarModel> UpdateAsync(SOAP.EjemplarWSClient.WSEjemplarModel WSEjemplarModel) {
            return base.Channel.UpdateAsync(WSEjemplarModel);
        }
        
        public void Delete(int codEjemplar) {
            base.Channel.Delete(codEjemplar);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int codEjemplar) {
            return base.Channel.DeleteAsync(codEjemplar);
        }
        
        public SOAP.EjemplarWSClient.WSEjemplarModel[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<SOAP.EjemplarWSClient.WSEjemplarModel[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public SOAP.EjemplarWSClient.WSEjemplarModel GetById(int codEjemplar) {
            return base.Channel.GetById(codEjemplar);
        }
        
        public System.Threading.Tasks.Task<SOAP.EjemplarWSClient.WSEjemplarModel> GetByIdAsync(int codEjemplar) {
            return base.Channel.GetByIdAsync(codEjemplar);
        }
    }
}
